[package]
name = "vulkano-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "^0.25.6"
vulkano = "^0.35.2"
vulkano-shaders = "^0.35.0"
winit = "^0.30.12"

[profile.dev]
opt-level = 1
